/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Message;

import Classes.DBConnection;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alpha
 */
public class Send_Message extends javax.swing.JInternalFrame {
    Connection conn =new DBConnection().connect();
     ResultSet rs =null;
     PreparedStatement pst =null;

    /**
     * Creates new form Send_Message
     */
    public Send_Message() {
        initComponents();
        lblsuccessfully.setVisible(false);
        lbldelete.setVisible(false);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void clear(){
        txtmessage.setText("");
    }
    byte[] attachment=null;
    
    public void secondEncrpt(){
      try{
          File image = new File (txtpath.getText());
          FileInputStream fis =new FileInputStream(image);
          
          ByteArrayOutputStream bos =new ByteArrayOutputStream();
          byte[] buf = new byte[1024];
          for(int readNum;(readNum=fis.read(buf))!=-1;){
              bos.write(buf,0,readNum);
          }
          
          attachment = bos.toByteArray();
      }
      catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
      }
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsender = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        lblsuccessfully = new javax.swing.JLabel();
        lbldelete = new javax.swing.JLabel();
        btn_access1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtpath = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbreciver = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btndelete2 = new javax.swing.JButton();
        txtmessage = new javax.swing.JTextField();
        btndelete3 = new javax.swing.JButton();
        pnlview = new javax.swing.JPanel();
        btnrecive = new javax.swing.JButton();
        btnsend2 = new javax.swing.JButton();
        btnsend3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Send Message ");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sender :");
        jLabel3.setToolTipText("");

        txtsender.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtsender.setForeground(new java.awt.Color(255, 255, 255));
        txtsender.setToolTipText("");

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/New Message_51px.png"))); // NOI18N
        btndelete.setToolTipText("Delete massage");
        btndelete.setBorder(null);
        btndelete.setContentAreaFilled(false);
        btndelete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ Message Filled_40px.png"))); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        lblsuccessfully.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblsuccessfully.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ok_51px_1.png"))); // NOI18N
        lblsuccessfully.setText("Sending Successfully");

        lbldelete.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lbldelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Attention_51px.png"))); // NOI18N
        lbldelete.setText("Delete Successfully");

        btn_access1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cancel_20px_1.png"))); // NOI18N
        btn_access1.setToolTipText("Access");
        btn_access1.setBorder(null);
        btn_access1.setContentAreaFilled(false);
        btn_access1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_access1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_access1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsender, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(lblsuccessfully, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldelete, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtsender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsuccessfully, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldelete, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                        .addGap(0, 22, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btn_access1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndelete))
        );

        btnsend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Message_51px.png"))); // NOI18N
        btnsend.setToolTipText("Text Message");
        btnsend.setBorder(null);
        btnsend.setContentAreaFilled(false);
        btnsend.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ Message Filled_40px.png"))); // NOI18N
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Conceder this Message", "Please send me attachment" }));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Edit Message ");

        cbreciver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrstor", "Clark" }));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setText("Reciver:");
        jLabel5.setToolTipText("");

        btndelete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Pin 2_51px_1.png"))); // NOI18N
        btndelete2.setToolTipText("Delete massage");
        btndelete2.setBorder(null);
        btndelete2.setContentAreaFilled(false);
        btndelete2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ Message Filled_40px.png"))); // NOI18N
        btndelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete2ActionPerformed(evt);
            }
        });

        btndelete3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Urgent Message_51px.png"))); // NOI18N
        btndelete3.setToolTipText("Delete massage");
        btndelete3.setBorder(null);
        btndelete3.setContentAreaFilled(false);
        btndelete3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ Message Filled_40px.png"))); // NOI18N
        btndelete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btndelete3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btndelete2)
                                        .addGap(32, 32, 32)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbreciver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cbreciver, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnsend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndelete2)))
                .addContainerGap())
        );

        btnrecive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Read Message_51px.png"))); // NOI18N
        btnrecive.setToolTipText("Read Message");
        btnrecive.setBorder(null);
        btnrecive.setContentAreaFilled(false);
        btnrecive.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ Message Filled_40px.png"))); // NOI18N
        btnrecive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreciveActionPerformed(evt);
            }
        });

        btnsend2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Attach_51px.png"))); // NOI18N
        btnsend2.setToolTipText("Text Message");
        btnsend2.setBorder(null);
        btnsend2.setContentAreaFilled(false);
        btnsend2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ Message Filled_40px.png"))); // NOI18N
        btnsend2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsend2ActionPerformed(evt);
            }
        });

        btnsend3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Message_51px.png"))); // NOI18N
        btnsend3.setToolTipText("Send Message");
        btnsend3.setBorder(null);
        btnsend3.setContentAreaFilled(false);
        btnsend3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ Message Filled_40px.png"))); // NOI18N
        btnsend3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsend3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setText("Main Box");

        javax.swing.GroupLayout pnlviewLayout = new javax.swing.GroupLayout(pnlview);
        pnlview.setLayout(pnlviewLayout);
        pnlviewLayout.setHorizontalGroup(
            pnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlviewLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(btnrecive, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsend3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsend2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(pnlviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlviewLayout.setVerticalGroup(
            pnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsend2)
                    .addGroup(pnlviewLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlviewLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(btnrecive))
                            .addGroup(pnlviewLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(btnsend3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        if(txtmessage.getText().trim().length()==0){
            
            JOptionPane.showMessageDialog(null,"Please Type Your Message Befor Sending");
            
        }
        else{
         try{
            String sql = "insert into tbl_SendMessageData (Sender_Name,Message,Ricever_Name) values(?,?,?)";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1,txtsender.getText());
            pst.setString(2,txtmessage.getText());
            pst.setString(3,cbreciver.getSelectedItem().toString());
                      
             
             pst.execute();
              lblsuccessfully.setVisible(true);
            
            clear();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
          try{
            String sql = "insert into tbl_SendMessageHead (Sender_Name,Reciver_Name,Status) values(?,?,?)";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1,txtsender.getText());
            pst.setString(2,cbreciver.getSelectedItem().toString());
            pst.setInt(3,0);
                      
             
             pst.execute();
              lblsuccessfully.setVisible(true);
            
            clear();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
         try{
            String sql = "insert into tbl_Attachment (Sender_Name,Reciver_Name,Att_Name,Att_Detail) values(?,?,?,?)";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1,txtsender.getText());
            pst.setString(2,cbreciver.getSelectedItem().toString());
            pst.setString(3,txtsender.getText()+"Attachment");
            secondEncrpt();
            pst.setBytes(4, attachment);
                      
             
             pst.execute();
              JOptionPane.showMessageDialog(null, "Successfully save Attachment");
              
            
            txtpath.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnsendActionPerformed

    private void btnreciveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreciveActionPerformed
        // TODO add your handling code here:
       // Recive_Message rm = Recive_Message();
       Message.Recive_Message m = new Message.Recive_Message();
        garage_management_software.Main.viewer.add(m);
        m.setVisible(true);
      
      
        
       
    }//GEN-LAST:event_btnreciveActionPerformed

    private void btnsend2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsend2ActionPerformed
        // TODO add your handling code here:
         Message.View_Attacment m = new Message.View_Attacment();
        garage_management_software.Main.viewer.add(m);
        m.setVisible(true);
       
    }//GEN-LAST:event_btnsend2ActionPerformed

    private void btnsend3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsend3ActionPerformed
        // TODO add your handling code here:
         Message.Read_Message m = new Message.Read_Message();
        garage_management_software.Main.viewer.add(m);
        m.setVisible(true);
        
    }//GEN-LAST:event_btnsend3ActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        lblsuccessfully.setVisible(false);
        lbldelete.setVisible(false);
        clear();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btn_access1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_access1ActionPerformed
        // TODO add your handling code here:
     this.dispose();
    }//GEN-LAST:event_btn_access1ActionPerformed

    private void btndelete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndelete3ActionPerformed

    private void btndelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        txtpath.setText(f.getAbsolutePath());
    }//GEN-LAST:event_btndelete2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_access1;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelete2;
    private javax.swing.JButton btndelete3;
    private javax.swing.JButton btnrecive;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnsend2;
    private javax.swing.JButton btnsend3;
    private javax.swing.JComboBox cbreciver;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbldelete;
    private javax.swing.JLabel lblsuccessfully;
    private javax.swing.JPanel pnlview;
    private javax.swing.JTextField txtmessage;
    private javax.swing.JTextField txtpath;
    public javax.swing.JLabel txtsender;
    // End of variables declaration//GEN-END:variables
}
