/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Utility;

import Classes.DBConnection;
import java.awt.Dimension;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alpha
 */
public class Access extends javax.swing.JInternalFrame {
     Connection conn =new DBConnection().connect();
     ResultSet rs =null;
     PreparedStatement pst =null;

    /**
     * Creates new form Access
     */
    public Access() {
        initComponents();
        fillcombo();
        
        
    }
    String empname;
   String selectemp="";
   byte[]  empsig=null;
   String sing ="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     public void Encypt(){
        try{
            FileInputStream file = new FileInputStream(txtsigpath.getText());
            FileOutputStream outStream = new FileOutputStream("Encrpted.jpg");
            byte k[]="NiTh5252".getBytes();
            SecretKeySpec key = new SecretKeySpec(k,"DES");
            Cipher enc = Cipher.getInstance("DES");
            enc.init(Cipher.ENCRYPT_MODE,key);
            CipherOutputStream cos = new CipherOutputStream(outStream,enc);
            byte[] buf = new byte[1024];
            int read;
            while((read=file.read(buf))!=-1){
             cos.write(buf,0,read);
            }
            
            file.close();
            outStream.flush();
            sing=cos.toString();
            cos.close();
            JOptionPane.showMessageDialog(null, "The File Encrypted Successfully");
            
        }
          catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
        //Decrypt method
       }
    public void secondEncrpt(){
      try{
          File image = new File (txtsigpath.getText());
          FileInputStream fis =new FileInputStream(image);
          
          ByteArrayOutputStream bos =new ByteArrayOutputStream();
          byte[] buf = new byte[1024];
          for(int readNum;(readNum=fis.read(buf))!=-1;){
              bos.write(buf,0,readNum);
          }
          
          empsig = bos.toByteArray();
      }
      catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
      }
    }
    public void fillcombo(){
        try{
            String sql="select * from tbl_Employee ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                 empname=rs.getString("Emp_Name");
                cbempname.addItem(empname);
                selectemp=(String)cbempname.getSelectedItem();
                txtusername.setText((String)cbempname.getSelectedItem());
                
            }
        }catch(Exception e){
            
        }
    }
    public void filltext(){
        selectemp=(String)cbempname.getSelectedItem();
        try{
        String sql="select * from tbl_User where User_Name='"+empname+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                
                String name =rs.getString("User_Name");
                String pass = rs.getString("Password");
                txtpassword.setText(pass);
                byte[] imagedata = rs.getBytes("Signature");
                format = new ImageIcon(imagedata);
                lbltest.setIcon(format);
            }
        }catch(Exception e){
            
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnclose1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnclose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbempname = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbusertype = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnempsave3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        btnempsave4 = new javax.swing.JButton();
        btnempsave5 = new javax.swing.JButton();
        lbltest = new javax.swing.JLabel();
        btnsigchoos = new javax.swing.JButton();
        txtsigpath = new javax.swing.JTextField();

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));

        btnclose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cancel_51px_2.png"))); // NOI18N
        btnclose1.setBorder(null);
        btnclose1.setContentAreaFilled(false);
        btnclose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclose1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(461, Short.MAX_VALUE)
                .addComponent(btnclose1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnclose1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cancel_51px_2.png"))); // NOI18N
        btnclose.setBorder(null);
        btnclose.setContentAreaFilled(false);
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Access Control");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        cbempname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbempnameMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbempnameMouseReleased(evt);
            }
        });
        cbempname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbempnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbempnameKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("Access Type");

        cbusertype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "Clark", "Super User", "Devision Head", "Employee" }));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("Employee Name");

        btnempsave3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Restart_48px.png"))); // NOI18N
        btnempsave3.setBorder(null);
        btnempsave3.setContentAreaFilled(false);
        btnempsave3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save Close_51px.png"))); // NOI18N
        btnempsave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempsave3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setText("Username");

        btnempsave4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Trash Can_51px.png"))); // NOI18N
        btnempsave4.setAutoscrolls(true);
        btnempsave4.setBorder(null);
        btnempsave4.setContentAreaFilled(false);
        btnempsave4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save Close_51px.png"))); // NOI18N
        btnempsave4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempsave4ActionPerformed(evt);
            }
        });

        btnempsave5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save as_51px_1.png"))); // NOI18N
        btnempsave5.setBorder(null);
        btnempsave5.setContentAreaFilled(false);
        btnempsave5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save Close_51px.png"))); // NOI18N
        btnempsave5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempsave5ActionPerformed(evt);
            }
        });

        btnsigchoos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hand With Pen_51px.png"))); // NOI18N
        btnsigchoos.setBorder(null);
        btnsigchoos.setContentAreaFilled(false);
        btnsigchoos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigchoosActionPerformed(evt);
            }
        });

        txtsigpath.setEditable(false);
        txtsigpath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsigpathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(cbusertype, 0, 220, Short.MAX_VALUE)
                    .addComponent(cbempname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(txtusername)
                    .addComponent(txtpassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsigpath, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbltest, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsigchoos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnempsave5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnempsave3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnempsave4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(cbempname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbusertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbltest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsigpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnempsave5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnempsave3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsigchoos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnempsave4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnempsave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempsave3ActionPerformed
        // TODO add your handling code here:
        filltext();
         String value1 = txtusername.getText();
        String value2 = txtpassword.getText();
        int value3 = cbusertype.getSelectedIndex();
        secondEncrpt();
       
                
       
         
        String sql="update tbl_User set User_Name='"+value1+"',Password='"+value2+"',Type='"+value3+"',Signature='"+empsig+"' where User_Name=?";
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1,selectemp);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Update Succsesfully");
                  }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
       

     

    

    }//GEN-LAST:event_btnempsave3ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jPanel2MouseClicked

    private void cbempnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbempnameMouseClicked
        // TODO add your handling code here:
      
       filltext();
    }//GEN-LAST:event_cbempnameMouseClicked

    private void cbempnameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbempnameMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbempnameMouseReleased

    private void cbempnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbempnameKeyPressed
        // TODO add your handling code here:
         selectemp=cbempname.getSelectedItem().toString();
       txtusername.setText(selectemp);
    }//GEN-LAST:event_cbempnameKeyPressed

    private void cbempnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbempnameKeyReleased
        // TODO add your handling code here:
        selectemp=cbempname.getSelectedItem().toString();
       txtusername.setText(selectemp);
    }//GEN-LAST:event_cbempnameKeyReleased

    private void btnempsave4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempsave4ActionPerformed
        // TODO add your handling code here:
         String sql="delete from tbl_User where User_Name=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,cbusertype.getSelectedItem().toString());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Delete Succsesfully");
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_btnempsave4ActionPerformed

    private void btnempsave5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempsave5ActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "insert into tbl_User (User_Name,Password,Type,Signature) values(?,?,?,?)";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1,txtusername.getText());
            pst.setString(2,txtpassword.getText());
            pst.setInt(3, cbusertype.getSelectedIndex());
            secondEncrpt();
            pst.setBytes(4, empsig);
            pst.execute();
              JOptionPane.showMessageDialog(null, "Successfully Save User ");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        txtusername.setText("");
        txtpassword.setText("");
        txtsigpath.setText("");
        
    }//GEN-LAST:event_btnempsave5ActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnclose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclose1ActionPerformed

    private void btnsigchoosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigchoosActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        txtsigpath.setText(f.getAbsolutePath());
        lbltest.setPreferredSize(new Dimension(40,14));
        lbltest.setIcon(new ImageIcon(txtsigpath.getText()));
    }//GEN-LAST:event_btnsigchoosActionPerformed

    private void txtsigpathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsigpathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsigpathActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnclose1;
    private javax.swing.JButton btnempsave3;
    private javax.swing.JButton btnempsave4;
    private javax.swing.JButton btnempsave5;
    private javax.swing.JButton btnsigchoos;
    private javax.swing.JComboBox cbempname;
    private javax.swing.JComboBox cbusertype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbltest;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtsigpath;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
private ImageIcon format =null;
}
